FIRST_NUMBER = 32
SECOND_NUMBER = 31
THIRD_NUMBER = 30

if FIRST_NUMBER == SECOND_NUMBER or SECOND_NUMBER == THIRD_NUMBER or THIRD_NUMBER == FIRST_NUMBER:
    print(0)
else:
    print(FIRST_NUMBER + SECOND_NUMBER + THIRD_NUMBER)